name: CI Build

# Perform CI builds for pull requests targeting the dev branches.

on: [push, pull_request, workflow_dispatch]

jobs:
  windows:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "x64 Windows MSVC Release",
            os: windows-latest,
            artifact: "gfxreconstruct-x64-dev-windows-msvc-release",
            type: "release",
            build_dir: "build",
            cc: "cl", cxx: "cl"
          }
        - {
            name: "x64 Windows MSVC Debug",
            os: windows-latest,
            artifact: "gfxreconstruct-x64-dev-windows-msvc-debug",
            type: "debug",
            build_dir: "dbuild",
            cc: "cl", cxx: "cl"
          }
    steps:
    - name: Clone repository
      uses: actions/checkout@v1
    - name: Run build script
      run: |
        python scripts\build.py --skip-check-code-style --skip-tests --config ${{ matrix.config.type }}
    - name: Prepare artifacts
      run: |
        copy LICENSE.txt ${{ matrix.config.build_dir }}\windows\x64\output\bin\
        copy LICENSE_ThirdParty.txt ${{ matrix.config.build_dir }}\windows\x64\output\bin\
        copy USAGE_desktop_D3D12.md ${{ matrix.config.build_dir }}\windows\x64\output\bin\
        copy USAGE_desktop_Vulkan.md ${{ matrix.config.build_dir }}\windows\x64\output\bin\
        copy layer\vk_layer_settings.txt ${{ matrix.config.build_dir }}\windows\x64\output\bin\
        move ${{ matrix.config.build_dir }}\windows\x64\output\bin gfxreconstruct-dev
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.config.artifact }}
        path: .\gfxreconstruct-dev

  win32:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "x86 Windows MSVC Release",
            os: windows-latest,
            arch: x86,
            artifact: "gfxreconstruct-x86-dev-windows-msvc-release",
            type: "release",
            build_dir: "build",
            cc: "cl", cxx: "cl"
          }
        - {
            name: "x86 Windows MSVC Debug",
            os: windows-latest,
            arch: x86,
            artifact: "gfxreconstruct-x86-dev-windows-msvc-debug",
            type: "debug",
            build_dir: "dbuild",
            cc: "cl", cxx: "cl"
          }
    steps:
    - name: Clone repository
      uses: actions/checkout@v1
    - name: Run build script
      run: |
        python scripts\build.py --skip-check-code-style --skip-tests --config ${{ matrix.config.type }} -a x86
    - name: Prepare artifacts
      run: |
        copy LICENSE.txt ${{ matrix.config.build_dir }}\windows\x64\output\bin\
        copy LICENSE_ThirdParty.txt ${{ matrix.config.build_dir }}\windows\x64\output\bin\
        copy USAGE_desktop_D3D12.md ${{ matrix.config.build_dir }}\windows\x64\output\bin\
        copy USAGE_desktop_Vulkan.md ${{ matrix.config.build_dir }}\windows\x64\output\bin\
        copy layer\vk_layer_settings.txt ${{ matrix.config.build_dir }}\windows\x64\output\bin\
        move ${{ matrix.config.build_dir }}\windows\x64\output\bin gfxreconstruct-dev
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.config.artifact }}
        path: .\gfxreconstruct-dev
